<a href="https://colab.research.google.com/github/mana-1538/AI_ML-practice-projects/blob/main/oops_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
class DataPreprocessor:
  def __init__(self,strategy='mean'):
    self.fill_values = None
    self.mean_ = None
    self.std_ = None
    self.strategy = strategy

  def fit(self, X):
    X = np.array(X,dtype = float)

    if (self.strategy=='mean'):
      self.fill_values= np.nanmean(X,axis =0)

    elif(self.strategy =='median'):
      self.fill_values= np.nanmedian(X,axis=0)

    elif(self.strategy =='zero'):
      self.fill_values = np.zeros(X.shape[1])

    elif(self.strategy=='mode'):
      vals, counts = np.unique(X,axis =0, return_counts=True)
      self.fill_values = vals[np.argmax(counts)]


    X_fill = np.where(np.isnan(X),self.fill_values,X)
    self.mean_ = np.nanmean(X_fill,axis=0)
    self.std_ = np.nanstd(X_fill,axis =0)
    return self

  def transform(self, X):
    if((self.mean_ is None) or (self.std_ is None) or (self.fill_values is None)):
      raise ValueError("ValueError : fit hasn't been called yet")

    X_fill = np.where(np.isnan(X),self.fill_values,X)
    X_std =(X_fill - self.mean_) / self.std_

    return X_std

  def fit_transform(self, X):
    result = self.fit(X).transform(X)

    print("Successfully transformed the array")
    return result

  def summary(self):
    print(f"filled values for each column are- {self.fill_values}")
    print(f"mean values for each column are - {self.mean_}")
    print(f"standard deviation values for each column are {self.std_}")



In [ ]:
import numpy as np

np.random.seed(42)
X_train = np.array([
    [1.0, 2.0, np.nan],
    [np.nan, 3.5, 1.0],
    [2.5, np.nan, 2.0],
    [3.0, 4.0, 1.5],
    [np.nan, 2.5, np.nan],
])

X_test = np.array([
    [2.0, np.nan, 1.0],
    [np.nan, 3.0, np.nan],
])

preprocessor = DataPreprocessor(strategy='mean')
X_train_clean = preprocessor.fit_transform(X_train)
X_test_clean = preprocessor.transform(X_test)  # fit NOT called again on test data

preprocessor.summary()

print("Cleaned train:\n", X_train_clean.round(3))
print("Cleaned test:\n", X_test_clean.round(3))


Successfully transformed the array
filled values for each column are- [2.16666667 3.         1.5       ]
mean values for each column are - [2.16666667 3.         1.5       ]
standard deviation values for each column are [0.65828059 0.70710678 0.31622777]
Cleaned train:
 [[-1.772 -1.414  0.   ]
 [ 0.     0.707 -1.581]
 [ 0.506  0.     1.581]
 [ 1.266  1.414  0.   ]
 [ 0.    -0.707  0.   ]]
Cleaned test:
 [[-0.253  0.    -1.581]
 [ 0.     0.     0.   ]]
